---
exclude_paths:
  - 'docs/**'
  - 'xii/django_river_admin/templates/**'
  - 'xii/django_river_admin/static/**'
  - 'examples/**/**'
  - 'demo/**/**'
  - '**/**/*.md'
  - '*.md'
  - 'pages/**/**'
  - 'test_settings.py'
  - 'manage.py'
  - 'test_urls.py'
  - '**/tests/**'
